#!/bin/bash

set -eux
cd "$(dirname "$0")"

GOBIN=$(go env GOBIN)
if [ -z "$GOBIN" ]; then
    GOBIN=$(go env GOPATH)/bin
fi

PATH="$PATH:$GOBIN" "../../../dev/tools/protoc/bin/protoc" \
    --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    -I "../../../dev/tools/protoc/include" \
    -I "." \
    ./*.proto
