---

- name: Common provisioning
  hosts: all

  tasks:
  - name: Install snap
    apt: { name: snapd }
    become: true

  - name: Install Go
    command: snap install go --channel {{ go_version }}/stable --classic
    become: true
  
  - command: go env GOPATH
    register: GOPATH
